// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Post struct {
	ID          pgtype.UUID
	Title       pgtype.Text
	Type        string
	Coupon      pgtype.Text
	Price       pgtype.Numeric
	DueDate     pgtype.Timestamptz
	Status      string
	Text        string
	Description pgtype.Text
	Link        pgtype.Text
	Fixed       bool
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
	Search      interface{}
}
