// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: post.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPosts = `-- name: CountPosts :one
SELECT COUNT(*)
FROM posts
`

func (q *Queries) CountPosts(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPosts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPost = `-- name: CreatePost :one
INSERT INTO public.posts (
    id,
    title,
    type,
    coupon,
    price,
    due_date,
    status,
    link,
    fixed,
    created_at,
    updated_at,
    deleted_at
  )
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12
  )
RETURNING id, title, type, coupon, price, due_date, status, text, description, link, fixed, created_at, updated_at, deleted_at, search
`

type CreatePostParams struct {
	ID        pgtype.UUID
	Title     pgtype.Text
	Type      string
	Coupon    pgtype.Text
	Price     pgtype.Numeric
	DueDate   pgtype.Timestamptz
	Status    string
	Link      pgtype.Text
	Fixed     bool
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRow(ctx, createPost,
		arg.ID,
		arg.Title,
		arg.Type,
		arg.Coupon,
		arg.Price,
		arg.DueDate,
		arg.Status,
		arg.Link,
		arg.Fixed,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.DeletedAt,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Type,
		&i.Coupon,
		&i.Price,
		&i.DueDate,
		&i.Status,
		&i.Text,
		&i.Description,
		&i.Link,
		&i.Fixed,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Search,
	)
	return i, err
}

const searchPosts = `-- name: SearchPosts :many
SELECT p.id,
  p.title,
  p.type,
  p.coupon,
  p.price,
  p.due_date,
  p.status,
  p.link,
  p.fixed,
  p.created_at,
  p.updated_at,
  p.deleted_at
FROM public.posts p
WHERE COALESCE(
    p.search @@ websearch_to_tsquery('simple', $1),
    TRUE
  )
  AND (
    p.type = ANY($2::text [])
    OR NOT $3
  )
  AND (
    (
      p.price >= $4
      AND p.price <= $5
    )
    OR NOT $6
  ) OFFSET $7
LIMIT $8
`

type SearchPostsParams struct {
	Search        pgtype.Text
	Types         []string
	FilterByType  interface{}
	MinPrice      pgtype.Numeric
	MaxPrice      pgtype.Numeric
	FilterByPrice interface{}
	Offset        int32
	Limit         int32
}

type SearchPostsRow struct {
	ID        pgtype.UUID
	Title     pgtype.Text
	Type      string
	Coupon    pgtype.Text
	Price     pgtype.Numeric
	DueDate   pgtype.Timestamptz
	Status    string
	Link      pgtype.Text
	Fixed     bool
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}

func (q *Queries) SearchPosts(ctx context.Context, arg SearchPostsParams) ([]SearchPostsRow, error) {
	rows, err := q.db.Query(ctx, searchPosts,
		arg.Search,
		arg.Types,
		arg.FilterByType,
		arg.MinPrice,
		arg.MaxPrice,
		arg.FilterByPrice,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchPostsRow
	for rows.Next() {
		var i SearchPostsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Type,
			&i.Coupon,
			&i.Price,
			&i.DueDate,
			&i.Status,
			&i.Link,
			&i.Fixed,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
